# Generated by Django 3.0.7 on 2020-06-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_article_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='password',
            field=models.CharField(default='12345', max_length=50),
        ),
    ]
